version: "3"
services:
  
  dtes:
    container_name: disposable-email-dtes
    image: ootech/dtes:latest
    build:
      context: .
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "3000:3000"
      - "25:2525"
    tty: true
    networks:
      - net1
    depends_on:
      - mongodb
    environment:
      - serverBaseUri=http://localhost:3000
      - mongoConnectUrl=mongodb://mongodb:27017/
      - appListenPort=3000
      - smtpPort=2525
      - allowAutocomplete=true
      - allowedDomains=temp.ootech.vn
      - jwtSecret=AH3M 1109 S3cR3T

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - net1
networks:
  net1:
